export const SET_DATA_BY_DAY = "SET_DATA_BY_DAY";
export const SET_DATA_BY_CLICK_OF_REGION = "SET_DATA_BY_CLICK_OF_REGION";
export const SET_INTIIAL_DATA_BY_FETCHING = "SET_INTIIAL_DATA_BY_FETCHING";
